/* This file is automatically generated based on your hardware design. */
#include "memory_config.h"

struct memory_range_s memory_ranges[] = {
	/* psu_ocm_ram_0_MEM_0 memory will not be tested since application resides in the same memory */
	/* psu_r5_0_atcm_MEM_0 memory will not be tested since it is a flash memory/non-writable memory */
	/* psu_r5_0_btcm_MEM_0 memory will not be tested since it is a flash memory/non-writable memory */
	{
		"psu_r5_ddr_0_MEM_0",
		"psu_r5_ddr_0",
		0x100000,
		2145386496,
	},
	{
		"psu_r5_tcm_ram_0_MEM_0",
		"psu_r5_tcm_ram_0",
		0x0,
		262144,
	},
};

int n_memory_ranges = 2;
